apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis-stunnel.fullname" . }}-config
  labels:
    app: {{ template "redis-stunnel.name" . }}
    chart: {{ template "redis-stunnel.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  stunnel.conf: |-
    foreground = yes
    debug = 7
    delay = yes
    socket = l:TCP_NODELAY=1
    socket = r:TCP_NODELAY=1
    [redis]
    accept = {{ .Values.config.listen }}:{{ .Values.config.portListen }}
    connect = {{ .Values.config.connect }}:{{ .Values.config.portConnect }}
    cert = /certs/cert.pem
    key = /certs/key.pem
