apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "redis-stunnel.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "redis-stunnel.name" . }}
    helm.sh/chart: {{ include "redis-stunnel.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "redis-stunnel.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "redis-stunnel.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: stunnel
            mountPath: /etc/stunnel/stunnel.conf 
            subPath: stunnel.conf 
          - name: certificates
            mountPath: /certs
      volumes:
      - name: stunnel
        configMap:
          name: {{ template "redis-stunnel.fullname" . }}-config
          defaultMode: 0755 
      - name: certificates
        secret:
          secretName: {{ .Values.ssl.secret }}
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
