apiVersion: v1
kind: Secret
metadata:
  name: stunnel-ssl-certs 
  labels:
    app: {{ template "redis-stunnel.fullname" . }}
    chart: {{ template "redis-stunnel.chart" . }} 
    release: {{ .Release.Service }} 
    heritage: {{ .Release.Name }} 
type: Opaque
data:
  cert.pem: {{ .Values.ssl.certificates.cert | b64enc }}
  key.pem: {{ .Values.ssl.certificates.key | b64enc }}
