apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-stunnel.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "redis-stunnel.name" . }}
    helm.sh/chart: {{ include "redis-stunnel.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: {{ include "redis-stunnel.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
